from setuptools import setup

# generated by: pandoc -f markdown_github -t rst -o README.rst README.md
try:
    README = open("README.rst").read()
except IOError:
    README = None

setup(
    name="pytest-expecter",
    version='0.2.2.post7',
    description="A fork of 'expecter' with better support for pytest.",
    long_description=README,
    author="Jace Browning",
    author_email="jacebrowning@gmail.com",
    py_modules=["expecter"],
    entry_points={
        "pytest11": [
            "pytest-expecter = expecter"
        ],
    },
    url="https://github.com/jacebrowning/pytest-expecter",
    license="BSD",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Plugins",
        "Framework :: Pytest",
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Topic :: Software Development :: Testing",
    ]
)
